### ISSUE TITLE
Backup excludes config-folder

### ISSUE THREAD

**Issue by vanMacG** [owncloud/updater#137]
As described in here:
https://forum.owncloud.org/viewtopic.php?f=31&t=28201&p=86844

Is this a bug or intended and the readme needs an update?

**Comment by VicDeo** [comment]
@vanMacG yes, since OC8 backup (and replace) is done only on items that are explicitly listed in 
https://github.com/owncloud/updater/blob/stable8/lib/files.json

Before that it tried to backup/replace all files and directories *except* specified causing a number of issues like this https://github.com/owncloud/updater/issues/64

**Comment by vanMacG** [comment]
@VicDeo Thanks for clearing things up. So "config/config.sample.php" is in the list and therefore should be in the backup? In my backups it isn't... And is there a reason to not backup config.php?

**Comment by te-online** [comment]
@vanMacG Are you sure the file was initially in place?
@VicDeo Can you say anything on why config.php is not backuped? Is that because of security reasons?

**Comment by VicDeo** [comment]
9.0 checkpoints have `config.php` inside

**Comment by VicDeo** [comment]
Closing as done
