### ISSUE TITLE
Add note that updates to new versions are always delayed a little bit

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/updater#183]
As users expect that the updater serves updates ASAP which gives wrong impression and a lot of people complain always.

See http://www.heise.de/forum/Open-Source/News-Kommentare/Owncloud-8-2-mit-neuen-Features-fuer-User-und-Admins/Ich-glaube-das-wars-dann-fuer-mich/posting-23831453/show/  for some more details. Probably just adding a note  like "Major updates are delayed up to one month until they are served by the updater application." somewhere.

cc @jospoortvliet as discussed
@karlitschek thoughts?

**Comment by karlitschek** [comment]
@VicDeo Isn't there a hint in the updater already that says exactly that?

**Comment by LukasReschke** [comment]
I think the confusion here is because we show an update to 8.1.3 and then no hint is shown that 8.2.0 is not available.

**Comment by RealRancor** [comment]
Yes, such a message was introduced with https://github.com/owncloud/updater/pull/114

**Comment by jospoortvliet** [comment]
yeah. It says a few days, something like 'up to a month' might be better, but it's there at least.

What about https://github.com/owncloud/updater/pull/185

**Comment by awikatchikaen** [comment]
Maybe adding an option to force update could be useful.
In my case, I don't want to switch on "beta" channel, but I would like to upgrade to 8.2. I understand the risk and currently opened bugs on this version aren't a problem for me now.

**Comment by jospoortvliet** [comment]
@awikatchikaen you can then just download the new zip and use the upgrade instructions on https://doc.owncloud.org/server/8.2/admin_manual/maintenance/upgrade.html#manual-upgrade-procedure

I hesistate to add that to the app as it would get a tad long. Also, I don't know how to link to the right documentation ;-)

@LukasReschke if you like the current solution, just push #185 through please? then we can close this and #186

**Comment by RealRancor** [comment]
Discussion about the other way around:

http://owncloud.10557.n7.nabble.com/Update-available-via-admin-interface-td16048.html

Just make the updates and upgrades instantly available.

**Comment by awikatchikaen** [comment]
The channels are a good idea. I can understand that actually the 8.2 is not push on "production" channel, but "stable" should always have the last public version...

**Comment by jospoortvliet** [comment]
@awikatchikaen I believe that that is how it is - stable has the latest version (incl 8.2.0 within hours of the release) and production is a bit behind (should have 8.2.1 by now, though).

If that is not the case than the process of updating the definitions on our side is broken, not the documentation ;-)

I don't know who makes the decision to make something available when and how, perhaps @karlitschek does that?

**Comment by RealRancor** [comment]
@jospoortvliet Yes, the release stuff is definitely broken. AFAIK stable and production have currently both 8.1.4 and 8.2.1 is not released yet via those channels.

The main problem here is, that this release stuff is just broken since ages. No one knows when an release will be available via the updater and whats the reason why an update is not available. Just see all that questions at forums, IRC and especially at the blogpost of the releases.

This is the most asked question since ages, coming up after each release. I probably could be rich if i got one dollar for each answer i have done about that. :see_no_evil: 

Ref: http://owncloud.10557.n7.nabble.com/Update-available-via-admin-interface-td16048.html

**Comment by karlitschek** [comment]
8.2.1 is now pushed out via the updater

**Comment by Flux3PO** [comment]
8.2.2 is out since the 22nd December but still not available in the Updater up. It seems that your Process is still not working 100%.

**Comment by jospoortvliet** [comment]
@karlitschek @cmonteroluque please, find a solution to this. 

In the mean time, I can only refer to https://www.youtube.com/watch?v=QZJC5ORod7I

**Comment by karlitschek** [comment]
discussed with @cmonteroluque I think we have a solution

**Comment by brevilo** [comment]
> Discussion about the other way around:
> http://owncloud.10557.n7.nabble.com/Update-available-via-admin-interface-td16048.html
> Just make the updates and upgrades instantly available.

I couldn't agree more with what's said there. The process **is** broken. What's the point of having a `stable` release channel when stable releases aren't immediately available? If the reason is to **really** make sure the new release doesn't break things then hold off a release on the `production` channel, but not on `stable`.

**Comment by rakekniven** [comment]
Please make stable release immediately available on stable channels.

**Comment by Flux3PO** [comment]
8.2.2 is finally available via Updater.. yay

Thanks
