### ISSUE TITLE
Web UI Authentication

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/updater#220]
Access to the web based updater has to be protected.

Idea:
Store some user password hash in a file within the updater and display a login form to the user when accessing the updater.

To think about:
smooth integration with owncloud core. we want the admin in the admin section to simply click a link
which opens the updater in a new tab/window.
In an ideal world no login form is displayed since we already know that the admin is authorized.

**Comment by DeepDiver1975** [comment]
![bildschirmfoto von 2016-01-28 15-58-41](https://cloud.githubusercontent.com/assets/1005065/12647976/066f7f58-c5d8-11e5-9153-7ca2b19d8ffa.png)

**Comment by karlitschek** [comment]
screenshots are an interesting way for cross repo issue linking ;-)

**Comment by LukasReschke** [comment]
> In an ideal world no login form is displayed since we already know that the admin is authorized.

We can write and read from the PHP session. While `$_SESSION['encrypted_session_data']` is encrypted the other stuff is not. So something like `$_SESSION['is_permitted_to_use_updater']`. Probably also including some timestamp to ensure that the permission was there recently. I guess storing the user name in there and actually looking up the permissions in the DB is out of question?

When we're thinking about a shared secret this should go more into the direction of a signature so that the actual shared secret is never exposed to the admin. Or change this for for each update / from time to time to ensure that ex-administrators (e.g. fired employees) cannot access the web UI in the future.

**Comment by DeepDiver1975** [comment]
> I guess storing the user name in there and actually looking up the permissions in the DB is out of question?

yes

**Comment by DeepDiver1975** [comment]
> We can write and read from the PHP session. While $_SESSION['encrypted_session_data'] is encrypted the other stuff is not. So something like $_SESSION['is_permitted_to_use_updater']. Probably also including some timestamp to ensure that the permission was there recently.

I like that

**Comment by DeepDiver1975** [comment]
But we still require a login form for direct access to the updater. Imagine the instance is already in maintenance mode and you cannot login but want to access the updater.

**Comment by karlitschek** [comment]
great idea. Let's use the session :-)

**Comment by karlitschek** [comment]
@DeepDiver1975 good point. but where doe the user get the hash from? still config.php ?

**Comment by VicDeo** [comment]
@karlitschek under these conditions (no info in session and broken OC) we can generate some hash on our own and put  it in a file that user can read via FTP

**Comment by karlitschek** [comment]
Hmm. This is tricky because this file shouldn't be accessible from the browser which is hard to guarantee if it is not guaranteed if .htaccess works.

**Comment by VicDeo** [comment]
@karlitschek it can be a *.php file with content as follows
```
<?php
somesecret
```

in this case it doesn't matter whether anyone can access this file or not.

**Comment by cmonteroluque** [comment]
@LukasReschke Hi, would you be able to help during this week to get this done? Sorry for the late request. @karlitschek would this work?

**Comment by LukasReschke** [comment]
> @LukasReschke Hi, would you be able to help during this week to get this done? Sorry for the late request. @karlitschek would this work?

Can't promise anything. There is other security related stuff that needs to be done as well. Also I consider 1 week before feature freeze a rather _VERY_ short timeline.

I can try to take a look and do my best but can't promise anything.

**Comment by LukasReschke** [comment]
That said, if the other stuff works and this is just the authentication: Should probably be doable.

**Comment by karlitschek** [comment]
@cmonteroluque I discussed with @LukasReschke and @DeepDiver1975. We will figure something out here.

**Comment by cmonteroluque** [comment]
OK thanks. Looking for tomorrow func freeze

**Comment by LukasReschke** [comment]
Ok. Have been thinking some more. Together with https://github.com/owncloud/core/pull/22238 I'm working about a cookieless solution. As the updater basically does remote execution by design this needs to have proper authentication. PR coming later…

**Comment by LukasReschke** [comment]
This is done with https://github.com/owncloud/core/pull/22255, https://github.com/owncloud/updater/pull/237 and https://github.com/owncloud/updater/pull/233

The authentication is implemented in the following way:

1. There is a config.php entry `updater.secret`. This value is not set by default.
2. If somebody opens the admin interface and clicks "Open updater", the value is set and after 24 hours cleaned (so that somebody with an old token can't do much harm). Also there can always only be one token. If somebody can't use the "Open updater" link for whatever reason they can just write that value into the config file themselves.
3. The token is sent with any request to the updater. If it matches the request passes.

I did it implement that way because a leaked token would be _very_ bad. It basically allows remote code execution. The way it is implemented now we don't have to worry about CSRF alike attacks plus old tokens do invalidate.

@VicDeo I'd love to make the expiration a tad smaller than 24 hours. Do we have any expectations for how long the updater app is expected to need for an upgrade?

**Comment by LukasReschke** [comment]
Plus, without a token by default we keep the risk of abuse way smaller. :smile:

**Comment by VicDeo** [comment]
@LukasReschke I suppose cron jobs are being skipped  in maintenance mode, aren't they?
If so, the token will not be invalidated until maintenance mode is over.

I think we can limit it to 2 hours and strongly advice not to use Web UI for big installations.
Most likely server timeout will happen before the token expiration.
