### ISSUE TITLE
Updater app and major upgrade?

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/updater#257]
Hi all. Sorry to say I am still a bit confused about the role of the Updater app. As I understand it, it is NOT for performing major upgrades, like from 8.2 -> 9.0?  Are there any issues specific to 9.0, other than the cool new CLI? Thanks!
@VicDeo @DeepDiver1975 @LukasReschke

**Comment by VicDeo** [comment]
@carlaschroder 
It is always recommended to use a distro package manager for updates.
Since 9.0  Updater is intended for both minor and major upgrades for users on shared hostings that have no ssh access/superuser privileges.

Here are some notes on usage https://github.com/owncloud/updater/wiki/Updater-9.0#updater-90

**Comment by carlaschroder** [comment]
Thanks @VicDeo

**Comment by carlaschroder** [comment]
I always forget to check the Wiki!
