### ISSUE TITLE
Print version found to be updated

### ISSUE THREAD

**Issue by mmattel** [owncloud/updater#292]
@VicDeo, @PVince81 

When running the updater manually, you get a statement about the current version running ``Current version is 9.0.0.19``, but not the version found to be upgraded to, only ``ownCloud daily is found online``.

````
sudo -uwww-data php updater/application.php
ownCloud updater 1.0 - CLI based ownCloud server upgrades
Checking system health.
 - file permissions are ok.
Current version is 9.0.0.19
ownCloud daily is found online
What would you do next?
  [0] download
  [1] upgrade
  [2] abort
 > 1
````

**Comment by mmattel** [comment]
Should also be printed on the admin page...

**Comment by PVince81** [comment]
Does daily have an actual version number ? Even if it's still 9.0.0.19 it could show as `9.0.0.19 [daily]` or something

**Comment by mmattel** [comment]
How is it determined that there is a higher version available than the running?
I always thought this is done via the sub version numbering.
Else this would get confusing somehow - or?

**Comment by VicDeo** [comment]
@mmattel 
this concerns daily channel only:
it might have the same version with the current version but have new commits merged. So there is no so much sense in  daily versions.

For other channels version is displayed correctly because this is a versionString from update feed: 
https://github.com/owncloud/updater/blob/master/src/Command/DetectCommand.php#L115

**Comment by VicDeo** [comment]
ah. 
I forgot that daily version is always `100.0.0.0` and this is _not_ an updater bug but a release server feature ;)

**Comment by VicDeo** [comment]
Fixed
