### ISSUE TITLE
Doesn't want to update to 9.0.3

### ISSUE THREAD

**Issue by Skippidar** [owncloud/updater#360]
I want to update it to 9.0.3, but updater says:

> Current version is 9.0.1.3
> No updates found online.

Selected channel is "stable"

**Comment by VicDeo** [comment]
@Skippidar sadly web updater has a couple of known issues so it is temporary inactive for 9.0.+

**Comment by RealRancor** [comment]
@VicDeo Because of this? https://github.com/owncloud/updater/issues/358

**Comment by PVince81** [comment]
There are issues with updating from 9.0.0 or 9.0.1 to 9.0.3 automatically resulting in integrity check errors: https://github.com/owncloud/updater/issues/358

We also can't tell the update to serve 9.0.2 for 9.0.0/9.0.1 because version 9.0.2 has trouble with encryption so everybody with encryption would get a failure there.

After the fix for https://github.com/owncloud/updater/issues/358 it will be possible to auto-update directly to 9.0.4 once released and enabled in the update server.

**Comment by PVince81** [comment]
We will release 9.0.4 soon, and plan to enable that one in the auto-updater if all update testing goes well.
