### ISSUE TITLE
Updater should be in Admin settings rather than separate window

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/updater#40]
As already discussed in the past in https://github.com/owncloud/core/issues/5279 and https://github.com/owncloud/apps/issues/1640

I hope after we merge the style fixes https://github.com/owncloud/updater/pull/39 we can look into moving the whole thing directly into admin settings. And making the »Backup« part less confusing.

cc @VicDeo @DeepDiver1975

**Comment by jancborchardt** [comment]
@te-online any updates so far?

@VicDeo @DeepDiver1975 it would be really important to get your input here.

**Comment by te-online** [comment]
@jancborchardt Not yet, but it's on my list. ;-) I think I can check the points mentioned above until end of the week.

**Comment by te-online** [comment]
Well, I made the changes from the list, but couldn't test the actual update process, yet. Going to https://apps.owncloud.com/updater.php?version=7.0.3 gives me an empty xml reply, so it always shows that ownCloud is up-to-date. Is there something wrong with the service?

Another problem is, that I don't know how to style the note for the backups, because their doesn't seem to be any predefined class for the admin-panel to structure things a bit.

**Comment by te-online** [comment]
What's next here? In my opinion the text and style can be kept like that for now – but that's giving feedback on my own work. There is obviously some space for improvements. (see screenshot)

![bildschirmfoto 2015-02-25 um 18 34 34](https://cloud.githubusercontent.com/assets/4127167/6376299/5179685c-bd1d-11e4-9b75-1b538b674bf8.png)

I'd like to do a pull request from the branch *move-to-master* as it is. That would mean someone has to manually check, what changed since then, I guess, because the code moved to another file due to the fact that the app was moved to admin. As you see, I'm a bit confused about that, maybe some git-expert may help, so that we can finish this ;-)

**Comment by VicDeo** [comment]
Done https://github.com/owncloud/updater/pull/82

**Comment by jancborchardt** [comment]
@VicDeo @te-online oh btw – does an the »Updater« entry show in the sidebar as well? Maybe @DeepDiver1975 needs to help to put that in.

**Comment by VicDeo** [comment]
@jancborchardt it's automatic
![updater](https://cloud.githubusercontent.com/assets/991300/6783442/cdff8d58-d18a-11e4-89a4-a7dc3256383a.png)

**Comment by te-online** [comment]
I thought about what you mentioned here, @VicDeo https://github.com/owncloud/updater/issues/86#issuecomment-83692759.

>when the whole OC instance went FUBAR admin tab is not accessible.

Would it be possible to provide an external page (like we removed with this) that only holds the backups? I mean would this page be accessible if the ownCloud inteface can't be loaded? The link to this page could be provided in the message after a *crash* happened while updating.

**Comment by VicDeo** [comment]
@te-online this is potentially unsafe

**Comment by te-online** [comment]
I mean the same way we did it before? So this was also more potentially unsafe than keeping it to the admin-page? I'm unsure whether this page can be independent while it depends on the login session of the user. But maybe it's just a trash-idea...

**Comment by VicDeo** [comment]
@te-online how are you going to prove that user seeing this page is admin when OC is  broken?

**Comment by te-online** [comment]
@VicDeo That's my question :smile:. Okay I see, this is not possible. So when OC is broken using the separate update/backups page, this page wasn't accessible either, because login couldn't be confirmed?

A light version of this approach would be to add a hint to the crash-message that backups exist and can be downloaded via ftp/whatever.
