### ISSUE TITLE
Command Line Updater says: is latest version

### ISSUE THREAD

**Issue by mcnesium** [owncloud/updater#94]
moved this from #89 as I felt like this is a different issue:

    mcnesium@fluse:/var/www/owncloud$ date
    Fr 13. Mär 11:25:19 CET 2015

    mcnesium@fluse:/var/www/owncloud$ cat version.php
    <?php
    $OC_Version = array(8,0,1,1);
    $OC_VersionString = '8.0.1';
    $OC_Channel = 'stable';
    $OC_Build = '2015-03-04T18:38:50+00:00 eb2ac86c5d645829477b327402a9881a3d6fdf2b';

    mcnesium@fluse:/var/www/owncloud$ sudo -u www-data php occ upgrade
    ownCloud is already latest version

**Comment by RealRancor** [comment]
Hi,

the upgrader app isn't providing such a functionality to upgrade from command line:

https://github.com/owncloud/updater/issues/76
https://github.com/owncloud/updater/issues/77

Ref to clarify this in the help banner: https://github.com/owncloud/core/issues/14864

**Comment by mcnesium** [comment]
[In the docs it says to use the command line tool to upgrade large installations](https://doc.owncloud.org/server/8.0/admin_manual/maintenance/update.html), thats why I tried to use it because of #89

**Comment by RealRancor** [comment]
Hi,

mhhh maybe thats not that clear. You need to use the updater app to get to the step where you need to click "Start update" and then you need to use the ./occ upgrade instead.

**Comment by karlitschek** [comment]
Hmm. I think we should clarify this in the documentation. The occ upgrade command executes the upgrade if the new owncloud is already downloaded and installed. This does _not_ do the same that the updater app does which is downloading a new owncloud version and updating it.
@carlaschroder What do you think?

**Comment by carlaschroder** [comment]
I think when people say "I think the docs are not clear!" need to give specific examples.

**Comment by carlaschroder** [comment]
Also, I need clarification on whether updating and upgrading are two different operations. It seems they are not, but when I first wrote the chapters on updating and upgrading I was told that they are different, and that the Updater app is only for point releases, and not for upgrading to the next major release. However, it seems that this is not so, per the discussion at https://github.com/owncloud/core/issues/14814 , which is still unresolved.

**Comment by te-online** [comment]
As far as I know (and @karlitschek pointed out), the updater app is for »preparing the update« (backup, download and unzip) and core has methods to »peform the update« when everything is prepared (this is the same for updates and upgrades in my opinion). This fact is neither clear in the docs nor in the interface.

@carlaschroder In the docs there should be added that the updater app is only an interface for manually downloading and unzipping the new version and that after that the actual upgrade process follows, which is exactly the same for manual and updater-app-aided updates.

I tried to explain that here https://github.com/owncloud/core/issues/14569#issuecomment-77353986 as well, because I was really confused by the update-process at first.

**Comment by RealRancor** [comment]
@te-online Had reported this here: https://github.com/owncloud/documentation/issues/948 which got fixed by https://github.com/owncloud/documentation/commit/6aa78377c443ce4dfd72ef0c69795f9dffccbe99 and https://github.com/owncloud/documentation/commit/d79a165d01487dfcceba54750c631c0562fb97f0

**Comment by te-online** [comment]
@RealRancor Thanks :+1:

**Comment by RealRancor** [comment]
@carlaschroder 
Probably can be closed as you have introduced the two fixes to the documentation above?

**Comment by carlaschroder** [comment]
@RealRancor Works for me!
